### ISSUE TITLE
Date incorrectly parsed for browsers in UTC+ timezones

### ISSUE THREAD

**Issue by trafton** [AlaskaAirlines/auro-pane#14]
## Describe the bug

[Flight Search needs to work correctly from any time zone ](https://dev.azure.com/itsals/E_Sell_Shop/_workitems/edit/640337)

When a user is using a browser in a time zone in Europe and Asia, i.e., UTC-0 through UTC-+12, this component will incorrectly parse the date resulting in it rendering the day  before even though the underlying data contains the correct date. 

## To Reproduce
1. Set the time zone of your computer to any positive time zone, e.g., Amsterdam.
2. Go to ascom and search for any flight.
3. When you get to the matrix results page, note that the shoulder dates are one off.
4. If you inspect the auro-pane element, you will see that it had the correct date, but was parsed incorrectly,

## Expected behavior
The auro-pane element will show the correct date regardless of the user's time zone.

## Screenshots
![image](https://user-images.githubusercontent.com/1517922/130125094-3254955e-84c2-413b-ba06-edeb5312d813.png)
![apcode](https://user-images.githubusercontent.com/1517922/130124896-7f62d5aa-7c98-4d16-a837-b13f46c2ebce.png)
![apcode2](https://user-images.githubusercontent.com/1517922/130124993-fcb12626-0317-4825-add8-10551c565226.png)

**Comment by blackfalcon** [comment]
This issue has been discussed with the Auro team and we are actively looking into a solution and potential release ASAP.
