### ISSUE TITLE
auro-pane: sticky small breakpoint

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/auro-pane#19]
## Is your feature request related to a problem? Please describe.
Auro-pane needs an option for a more shallow padding on the element to fit more flight result shoulder dates in the auro-carousel.

## Describe the solution you'd like
A new attribute that locks the pane to a specific size.

**Comment by blackfalcon** [comment]
Passing this off to @leeejune for follow-up with the designer requesting this variant on the element.
