### ISSUE TITLE
MOW Auro-pane buttons (shoulder dates) are shortened and are not consistent with flight search shopping experience

### ISSUE THREAD

**Issue by gtaylor24** [AlaskaAirlines/auro-pane#22]
## Describe the bug
The shoulder dates (blue buttons) on the auro-pane are shortened and are more spherical when shopping in MOW

## To Reproduce
1. Open up MOW and search for any flight.
2. When the Device is below a 660px display the shoulder dates in the auro-pane are shortened.
3. NOTE: This seems to be more accentuated in a safari browser. I had a difficult time replicating this in chromes mobile emulator 

## Expected behavior
The shoulder dates in MOW are expected to match more consistently with the flight search micro site

## Screenshots
MOW example on what I believe is an iPhone not 100 percent sure of the resolution:
![image](https://user-images.githubusercontent.com/99680516/171930617-894b572c-4b19-4c08-89d3-ea537de16937.png)

## Smartphone (please complete the following information):
 - Device: iPhone 11, 12
 - OS: iOS
 - Browser: Safari
 - Version: Unknown

## Additional context
Here is an example of some browser testing done where we can see the media query only specifying the length of the shoulder date in the auto pane when the width of the display is 660px and above:
![image](https://user-images.githubusercontent.com/99680516/171931078-85cb1a80-d27e-4b77-b193-5773cfd30a18.png)

I do not see a media query show up that impacts the height or min-width of the shoulder date in the auto pane when the display is less that 660px which would break into the mobile view. I don't know if that is the solution but this is observed in the screenshot above

**Comment by braven112** [comment]
Thanks @gtaylor24 we'll review this with the designers next week and get this on our roadmap based off their feedback.

**Comment by blackfalcon** [comment]
This is interesting. The issue only appears on iOS. It doesn't repro on Safari responsive mode? 

<img width="1174" alt="Screen Shot 2022-06-03 at 12 49 29 PM" src="https://user-images.githubusercontent.com/181089/171939769-bb15c2e7-6fe2-4ba7-8509-ef3ba25ee74d.png">

**Comment by blackfalcon** [comment]
Digging into this more, the issue is not with the element, but the MOW baseline CSS. MOW has `html` set at `10px` which is a wildly out-of-date concept and creates issues like this. 

All of Auro is based on a default of `16px`. Because of this, Auro pane inside of carousel is way small because of the use of REMs, which is basing its styles on the `html` element and cannot be changed via a parent font-size change. 

So this is not a bug per-say, but more so an issue with the surrounding influences.

**Comment by blackfalcon** [comment]
This issue is not specific to Auro pane, but related to the structure of the consuming application. An issue was created in mobile web shopping that references this issue and a PR that corrected a similar issue with MOW.
