### ISSUE TITLE
auro-pane: selected attribute reflection

### ISSUE THREAD

**Issue by ftaylor-alaska** [AlaskaAirlines/auro-pane#23]
## Describe the bug
In a Svelte application, I cannot select the pane by querying the 'select' attribute, because the property is not reflected. I need to get the element's position so that I can center the pane when it is in a carousel.

## Expected behavior
The 'selected' attribute is rendered on the element.

## Relevant Framework 
- Svelte

**Comment by geoffrich** [comment]
As a note here, this is a _slightly_ different use case than why we normally reflect properties to attributes.

In most other components, we reflect a property when the component uses the presence of that attribute for styling, e.g. `:host([disabled])`.

In this case, auro-pane does not use the selected attribute for styling, but the consumer of this component wants to be able to query for an auro-pane based on whether it has been selected, e.g. `document.querySelectorAll('auro-pane[selected]')`. It's a subtle difference, but worth understanding.

IMO, this means that this is technically a feature request, not a bug.
