### ISSUE TITLE
No keyboard focus states

### ISSUE THREAD

**Issue by aesthetiques** [AlaskaAirlines/auro-pane#28]
## Describe the bug
When navigating across a de-selected auro-pane, the focus states will not appear.

## To Reproduce
1. Go to https://www.alaskaair.com/search-qa/results?O=SEA&D=LAX&OD=2022-10-16&OT=Anytime&RT=false&ShoppingMethod=standard
2. Tab through the elements until you reach the "shoulder dates" (auro panes) shown below:
![image](https://user-images.githubusercontent.com/25255197/188238870-dc856982-da09-4b4f-a1a5-6e02f82039d1.png)
3. No focus states show on the panes, other than the currently selected day

## Expected behavior
When tabbing through the carousel of panes, we expect for each 

## Desktop (please complete the following information):
 - OS: macOS Big Sur
 - Browser: Chrome, Firefox 
 - Version: latest stable

**Comment by blackfalcon** [comment]
Verified https://auro.alaskaair.com/components/auro/pane/
