### ISSUE TITLE
auro-pane: option to show price in disabled state

### ISSUE THREAD

**Issue by erikalanghauser** [AlaskaAirlines/auro-pane#30]
## Is your feature request related to a problem? Please describe.
On the new flight results page, users were making back-to-back calls to the flights results API by clicking available shoulder dates while results were still loading. This resulted in buggy behavior where incorrect results would show intermittently before the correct result returned. In order to prevent guests from clicking shoulder dates while results are still loading, we used the inactive pane. Once loaded, the pane is active again. This works, except it is jarring that the prices disappear and then reappear. 

We would like to propose a new option to show the price in the inactive/disabled state, so guests don't lose their reference each time they click a new shoulder pane. Design would be the same, except we would allow price to continue to show where the '--' currently does.

## Describe the solution you'd like
We would like a new option to continue to show price in the inactive state.
![image](https://user-images.githubusercontent.com/34354487/194671981-4fcbb9ab-5241-45e9-a44f-814e11c09611.png)

## Describe alternatives you've considered
We released our MVP experience with showing the inactive loading state after the guest selects a new shoulder date and until the results are loaded, but the guest then loses reference to the prices that they saw before the click.
![image](https://user-images.githubusercontent.com/34354487/194672129-def4697b-ce96-4f32-9813-7479a1b312d9.png)

Show active state design with price but disable clicking - there is concern this could cause rage clicking and we want to avoid showing something as active and clickable when it's not ready yet.

## Additional context
CCing @isaiahscheel in case there is additional technical context he can provide.

## Exit criteria 

This issue will be considered closed once the auro-pane element is showing the price as requested by design when the pane is disabled.

**Comment by blackfalcon** [comment]
@Lewisfuuh we should get this in an upcoming sprint ASAP. Low-hanging fruit that the team has been waiting to be prioritized.

**Comment by blackfalcon** [comment]
@jordanjones243 I am bringing this back to make sure that we didn't miss something. In the update you did, you removed the logic that replaces the price with `--`. Ok, this works if `this.price` has a value. When updating the docsite we had examples where `price=""` was an empty string. The UI for that looked broken. 

I am wondering that if there is a case where `price` is empty, we then show the `--`? 

My concern is that if we release this and there are empty prices out there, that will result in a broken-looking UI. @erikalanghauser do you have any insight on this?

**Comment by blackfalcon** [comment]
This is what it looks like of `price` is left empty. 

<img width="446" alt="Screen Shot 2022-12-27 at 5 01 38 PM" src="https://user-images.githubusercontent.com/181089/209741602-9f4171b3-d94d-4c90-9b08-737940d78e81.png">

**Comment by jordanjones243** [comment]
@blackfalcon I did notice this when working on the issue and also thought that it looked strange in the UI, but did not bring up potential changes to this, as I would've thought the designers might have said something. In the future, I will bring something like this up to the team if I have questions about it.

**Comment by erikalanghauser** [comment]
@blackfalcon @jordanjones243 - If the price is returning empty, we should still place a -- in place rather than show it as blank.
Thanks!
