### ISSUE TITLE
Nothing is displayed in UI when price is empty

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-pane#34]
## Describe the bug

When `price=""`, the UI displays nothing at all.

## Expected behavior

When `price=""`, we want the pane to display `--` in place of a price.

## Screenshots
<img width="324" alt="Screen Shot 2023-01-04 at 2 35 16 PM" src="https://user-images.githubusercontent.com/55807669/210663034-e0593d58-5c97-4160-917d-ceb90cfac82f.png">

**Comment by blackfalcon** [comment]
Duplicate issue of https://github.com/AlaskaAirlines/auro-pane/issues/35
