### ISSUE TITLE
Automated add to project process is broken

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-pane#58]
### Please verify the version of auro-pane you have installed

@latest

### Please describe the bug

See https://github.com/AlaskaAirlines/auro-pane/actions/runs/8218891095/job/22476262303

```shell
Error: Request failed due to following response errors:
 - Your token has not been granted the required scopes to execute this query. The 'projectV2' field requires one of the following scopes: ['read:project'], but your token has only been granted the: ['repo', 'workflow'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.
 - Your token has not been granted the required scopes to execute this query. The 'id' field requires one of the following scopes: ['read:project'], but your token has only been granted the: ['repo', 'workflow'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.
```

### Reproducing the error

This issue cannot be reproduced on the Auro docsite

### Expected behavior

The automated process should be successfully executed. 

### Additional context

n/a

### Exit criteria

This issue can be closed once the reason why this process is not working is resolved and the automated process works as expected.

**Comment by Patrick-Daly-AA** [comment]
I encountered this same error when using the github CLI just the other day.  I was able to fix it on the CLI with re-authenticating with this line: gh auth login --scopes read:project

It looks like github may have made a change to the default scope for their GraphQL end point.

**Comment by Patrick-Daly-AA** [comment]
@fajar-apri-alaska , any chance you can investigate this one?  I have a theory in the comment above, and we have a suspicion that this is likely a problem which we will need to fix in the web component generator for all our components.

Feel free to reach out if you have any questions.

**Comment by fajar-apri-alaska** [comment]
> @fajar-apri-alaska , any chance you can investigate this one? I have a theory in the comment above, and we have a suspicion that this is likely a problem which we will need to fix in the web component generator for all our components.
> 
> Feel free to reach out if you have any questions.

Sure, I will try to find out first.

**Comment by blackfalcon** [comment]
I resolved this issue by re-adding the same personal access tokens o_O

Can not understand why this broke, but it appears to be working now.
